Use -target-feature for MTE
Instead of setting -march, use clang's -target-feature functionality
to enable MTE. Some projects set -march which may conflict with MTE's
usage. Using -target-feature to enable MTE removes any clang command
line ordering issues.

History:
* Originally submitted as e4e44046c18178ed5390d35e5661815bea2aab9d
* reverted in be835f2a047bca48b5f0e41ce32eb60e1d93a5e4 due to
  bug 371029823
* Prematurely resubmitted as 7b361fca0bb05c04d6bcc7403cba7d11cd912191
  and then subsequently reverted in
  6577c9c69f08c14f4b5035773ba4efb5c54bf7e6 as the fix for bug 371029823
  had not yet landed.

Fixes the following compile failures on _fullmte builds:

  vendor/google/services/LyricCameraHAL/src/lyric/api/algo/data_types/local_tone_mapping_data_v1.cc
  vendor/google/services/LyricCameraHAL/src/lyric/api/algo/data_types/local_tone_mapping_data_v1.cc:209:34: error: always_inline function 'vpaddq_f16' requires target feature 'fullfp16', but would be inlined into function 'GridMeanNeon' that is compiled without support for 'fullfp16'
    209 |       vmulq_f16(norm, vpaddq_f16(vpaddq_f16(slope_bias[0], slope_bias[1]),
        |                                  ^
  vendor/google/services/LyricCameraHAL/src/lyric/api/algo/data_types/local_tone_mapping_data_v1.cc:210:34: error: always_inline function 'vpaddq_f16' requires target feature 'fullfp16', but would be inlined into function 'GridMeanNeon' that is compiled without support for 'fullfp16'
    210 |                                  vpaddq_f16(slope_bias[2], slope_bias[3])));

Bug: 366222162
Test: compiles and boots
Change-Id: I821b310908dd9ff2aeaa81459762286590337eaf