capture NoClassDefFoundError
The generated code should capture NoClassDefFoundError, since mainline
module could run on older devices. The catch should be replaced to sdk
version check once the version is bumped.

Test: presubmit
Change-Id: Iba088848cbde5d395e41ac9b0f5bb84334bc0ca3