Revert "use new GKI kernel location"
Revert "Update kernel to builds 6888926"

Revert submission 1454075-2020-10-07-gki-update

Reason for revert: Looks like this topic changes caused daily build broken, the error log as:

error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)

I tried to revert this topic first and then feel free to revert revert it.

Reverted Changes:
Ie74ca26e8:use new GKI kernel location
Ibff0d9638:Update kernel to builds 6889747
I693476e82:Update kernel to builds 6888926
I35d7f320c:Update kernel to builds 6888926
Id221a7a30:Update kernel to builds 6888926
I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
I991f9a6af:Allow downstream devices to customize vendor modul...
I598630e09:load kernel, kernel modules from updated locations...

Bug: 170451791
Change-Id: I4d8f18a7c80eb92cb475c48e1dcf04ceabd08984